<a href="https://colab.research.google.com/github/prakash-bisht/Pytorch_Basic/blob/master/pytorch_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Create a 2x3 tensor of ones and multiply it by 5. Then convert it to a NumPy array.
import torch
tensor = torch.ones(2,3) * 5
sol = tensor.numpy()
sol

array([[5., 5., 5.],
       [5., 5., 5.]], dtype=float32)

In [ ]:
# Create a tensor with requires_grad=True. Perform a simple mathematical operation on it and compute the gradient.
a = torch.tensor(2.0,requires_grad=True)
b = a ** 2
b.backward()
a.grad

tensor(4.)

In [ ]:
# Define a simple feedforward neural network with one hidden layer using nn.Module.
import torch.nn as nn
class NN(nn.Module):
  def __init__(self):
    super(NN,self).__init__()
    self.fc1 = nn.Linear(10,5)
    self.fc2 = nn.Linear(5,1)

  def forward(self,x):
    x = torch.relu(self.fc1(x))
    x = self.fc2(x)
    return x

model = NN()
model

NN(
  (fc1): Linear(in_features=10, out_features=5, bias=True)
  (fc2): Linear(in_features=5, out_features=1, bias=True)
)

In [ ]:
# Train a simple neural network on random data for five epoch using an optimizer and a loss function.
import torch.optim as optim
inputs = torch.randn((10,10))
targets = torch.randn((10,1))

model = NN()
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(),lr=0.01)

for i in range(5):
  optimizer.zero_grad()
  outputs = model(inputs)
  loss = criterion(outputs,targets)
  loss.backward()
  optimizer.step()
  print(f"Epoch {i} loss : {loss.item()}")


Epoch 0 loss : 1.93307363986969
Epoch 1 loss : 1.8781369924545288
Epoch 2 loss : 1.8259385824203491
Epoch 3 loss : 1.776182770729065
Epoch 4 loss : 1.7286170721054077


In [ ]:
# Create a DataLoader for a random dataset and iterate through the batches.
from torch.utils.data import DataLoader,TensorDataset
data = torch.randn(100, 10)
labels = torch.randint(0,2,(100,))
dataset = TensorDataset(data,labels)
data_loader = DataLoader(dataset,shuffle=True,batch_size = 5)
for data_,label_ in data_loader:
  print(data_,label_)
  break

tensor([[ 4.6905e-01, -4.5387e-01,  9.7574e-01,  2.1553e+00,  3.4136e-01,
          9.6963e-01, -1.0813e+00, -3.2620e-01, -1.3422e-01, -8.5931e-02],
        [-8.4437e-01, -1.2379e+00, -1.9899e+00, -1.0764e+00, -1.0988e+00,
         -1.8087e-01, -3.8964e-01, -5.6129e-01,  1.7718e+00, -1.0205e+00],
        [-2.7559e-01,  1.6304e-02, -1.4101e+00,  3.5945e+00, -6.0186e-01,
          1.1482e+00,  5.0462e-01,  2.3491e-01, -1.5563e+00,  7.6732e-01],
        [ 3.4500e-03, -5.9397e-01,  2.0407e-02, -2.7533e-01, -1.2208e+00,
         -9.3741e-01, -8.1940e-02, -4.0699e-01, -1.4074e-01, -3.4657e-01],
        [ 1.2279e+00,  1.3492e+00, -2.0786e+00,  1.0967e+00,  2.5876e-01,
          8.2271e-02,  1.3930e-01, -1.2209e-01, -7.5978e-01,  6.7253e-01]]) tensor([1, 1, 1, 0, 1])


In [ ]:
# Save a PyTorch model's state dictionary and load it back.
import torch
torch.save(model.state_dict(),'model.pth')
model = NN()
model.load_state_dict(torch.load('model.pth'))

<All keys matched successfully>

In [ ]:
# Load a pre-trained model from torchvision and modify the last layer for a different number of classes.
import torchvision.models as models
model = models.resnet152(pretrained=True)
model.fc = nn.Linear(model.fc.in_features,10)
print(model)

/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet152_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet152_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/resnet152-394f9c45.pth" to /root/.cache/torch/hub/checkpoints/resnet152-394f9c45.pth
100%|██████████| 230M/230M [00:02<00:00, 105MB/s]


ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 

In [ ]:
# Demonstrate gradient clipping during training.
# Calculate gradients for the parameters of the neural network during backpropagation.
# Check if the gradients exceed a predefined threshold.
# If the gradients exceed the threshold, scale them down so that they are within the desired range.
# Update the model parameters using the scaled gradients.
import torch.optim as optim
inputs = torch.randn((10,10))
targets = torch.randn((10,1))

model = NN()
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(),lr=0.01)

for i in range(5):
  optimizer.zero_grad()
  outputs = model(inputs)
  loss = criterion(outputs,targets)
  loss.backward()
  torch.nn.utils.clip_grad_norm_(model.parameters(),max_norm=1.0)
  optimizer.step()
  print(f"Epoch {i} loss : {loss.item()}")



Epoch 0 loss : 1.2967824935913086
Epoch 1 loss : 1.27652907371521
Epoch 2 loss : 1.2566492557525635
Epoch 3 loss : 1.2371275424957275
Epoch 4 loss : 1.2179410457611084


In [ ]:
# Initialize the weights of a neural network layer with a normal distribution.
import torch
import torch.nn as nn

class NN_(nn.Module):
  def __init__(self) -> None:
    super(NN_,self).__init__()
    self.fc1 = nn.Linear(10,5)
    self.fc2 = nn.Linear(5,1)
    self.initialize_weights()

  def initialize_weights(self):
    nn.init.normal_(self.fc1.weight,mean=0.0,std=1.0)
    nn.init.normal_(self.fc2.weight,mean=0.0,std=1.0)

  def forward(self,x):
    x = torch.relu(self.fc1(x))
    x = self.fc2(x)
    return x

model = NN_()
print(model)

NN_(
  (fc1): Linear(in_features=10, out_features=5, bias=True)
  (fc2): Linear(in_features=5, out_features=1, bias=True)
)


In [ ]:
# Here's why learning rate schedulers are important:
# Convergence Speed: Initially, you might want a higher learning rate to make large updates to the parameters and quickly converge towards a minimum of the loss function.
#  However, as training progresses, you typically want to decrease the learning rate to make smaller, more precise updates,
#  allowing the model to fine-tune its parameters.
import torch.optim as optim
inputs = torch.randn((10,10))
targets = torch.randn((10,1))

model = NN()
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(),lr=0.01)
scheduler = optim.lr_scheduler.StepLR(optimizer,step_size=1,gamma=0.1)

for i in range(5):
  optimizer.zero_grad()
  outputs = model(inputs)
  loss = criterion(outputs,targets)
  loss.backward()
  optimizer.step()
  scheduler.step()
  print(f"Epoch {i} loss : {loss.item()} Learning rate: {scheduler.get_last_lr()}")


Epoch 0 loss : 0.9277095794677734 Learning rate: [0.001]
Epoch 1 loss : 0.9137060046195984 Learning rate: [0.0001]
Epoch 2 loss : 0.9123532176017761 Learning rate: [1e-05]
Epoch 3 loss : 0.9122183918952942 Learning rate: [1.0000000000000002e-06]
Epoch 4 loss : 0.912204921245575 Learning rate: [1.0000000000000002e-07]


In [ ]:
# Convert a batch of class indices to one-hot encoded vectors.
labels = torch.tensor([0, 1, 2, 1])
one_hot = torch.nn.functional.one_hot(labels,num_classes=5)
one_hot

tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 1, 0, 0, 0]])

In [ ]:
x = torch.tensor(2.0,requires_grad=True)
y = x ** 2
y_ = y.detach()
print("Requires grad:", y.requires_grad)
print("Requires grad after detach:", y_.requires_grad)

Requires grad: True
Requires grad after detach: False


In [ ]:
# Implement Xavier (Glorot) initialization for the weights of a neural network layer.
import torch
import torch.nn as nn

class NN_(nn.Module):
  def __init__(self) -> None:
    super(NN_,self).__init__()
    self.fc1 = nn.Linear(10,5)
    self.fc2 = nn.Linear(5,1)
    self.initialize_weights()

  def initialize_weights(self):
    nn.init.xavier_uniform_(self.fc1.weight)
    nn.init.xavier_uniform_(self.fc2.weight)

  def forward(self,x):
    x = torch.relu(self.fc1(x))
    x = self.fc2(x)
    return x

model = NN_()
print(model)


NN_(
  (fc1): Linear(in_features=10, out_features=5, bias=True)
  (fc2): Linear(in_features=5, out_features=1, bias=True)
)


In [ ]:
#  Implement a custom activation function (e.g., Swish) in PyTorch and use it in a neural network.
class Swish(nn.Module):
  def forward(self,x):
    return x * torch.sigmoid(x)

class custom_NN(nn.Module):
  def __init__(self):
    super(custom_NN,self).__init__()
    self.fc1 = nn.Linear(10,5)
    self.swish = Swish()
    self.fc2 = nn.Linear(5,1)


  def forward(self,x):
    x = self.swish(self.fc1(x))
    x = self.fc2(x)
    return x

model_ = custom_NN()
print(model_)


custom_NN(
  (fc1): Linear(in_features=10, out_features=5, bias=True)
  (swish): Swish()
  (fc2): Linear(in_features=5, out_features=1, bias=True)
)


In [ ]:
# Implement a custom neural network layer that performs a specific operation (e.g., adding a constant to the input).
class add_constant(nn.Module):
  def __init__(self,constant):
    super(add_constant,self).__init__()
    self.constant = constant

  def forward(self,x):
    return x + self.constant

class const_NN(nn.Module):
  def __init__(self):
    super(const_NN,self).__init__()
    self.fc1 = nn.Linear(10,5)
    self.add_const = add_constant(5)
    self.fc2 = nn.Linear(5,1)

  def forward(self,x):
    x = torch.relu(self.fc1(x))
    x = self.add_const(x)
    x = self.fc2(x)
    return x

model_ = const_NN()
print(model_)

const_NN(
  (fc1): Linear(in_features=10, out_features=5, bias=True)
  (add_const): add_constant()
  (fc2): Linear(in_features=5, out_features=1, bias=True)
)


In [ ]:
#  Implement gradient accumulation for training a neural network with a large batch size that doesn't fit into memory.
import torch.optim as optim
model = NN_()
optimizer = optim.SGD(model.parameters(),lr=0.01)
criterion = nn.MSELoss()

accumulation_steps = 4
inputs = torch.randn(40,10)
targets = torch.randn(40,1)
model.train()
optimizer.zero_grad()

for i in range(0,len(inputs),accumulation_steps):
  batch_input = inputs[i:i + accumulation_steps]
  batch_target = targets[i:i + accumulation_steps]
  output = model(batch_input)
  loss = criterion(output,batch_target)
  loss.backward()

  if (i // accumulation_steps + 1) % accumulation_steps == 0:
    optimizer.step()
    optimizer.zero_grad()

print(f"loss {loss.item()}")

loss 0.4693182706832886


In [ ]:
# Implement mixed precision training
from torch.cuda.amp import autocast,GradScaler
model = NN_().cuda()
optimizer = optim.SGD(model.parameters(),lr=0.01)
criterion = nn.MSELoss()

scaler = GradScaler()
inputs = torch.randn(40,10).cuda()
targets = torch.randn(40,1).cuda()

for epoch in range(20):
  optimizer.zero_grad()
  with autocast():
    output = model(inputs)
    loss = criterion(output,targets)

  scaler.scale(loss).backward()
  scaler.step(optimizer)
  scaler.update()

print(f"loss {loss.item()}")

loss 1.4324105978012085


In [ ]:
# Implement model checkpointing to save and load model state during training.
model = NN_()
optimizer = optim.SGD(model.parameters(),lr=0.01)
criterion = nn.MSELoss()

checkpoint = {
    'epoch':1,
    'model_state_dict': model.state_dict(),
    'optimizer_state_dict': optimizer.state_dict(),
    'loss': 0.5,
}

torch.save(checkpoint,'checkpoint.pth')

# checkpoint = torch.load('checkpoint.pth')
model.load_state_dict(checkpoint['model_state_dict'])
optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
epoch = checkpoint['epoch']
loss = checkpoint['loss']
print(f"loaded model at epoch {epoch} with loss {loss}")

loaded model at epoch 1 with loss 0.5


In [ ]:
# Fine-tune a pre-trained ResNet model on a new dataset.
import torchvision.models as models

model = models.resnet18(pretrained=True)
for param in model.parameters():
  param.requires_grad = False

model.fc = nn.Linear(model.fc.in_features,10)
for param in model.fc.parameters():
  param.requires_grad = True

optimizer = optim.SGD(model.fc.parameters(), lr=0.01)
criterion = nn.CrossEntropyLoss()

# Assuming inputs and targets are your new dataset
inputs = torch.randn((10, 3, 224, 224))
targets = torch.randint(0, 10, (10,))

outputs = model(inputs)
loss = criterion(outputs, targets)
loss.backward()
optimizer.step()

print(f'Loss: {loss.item()}')

Loss: 2.510972499847412


In [ ]:
# Implement early stopping in a training loop to prevent overfitting.
model = NN_()
optimizer = optim.SGD(model.parameters(),lr=0.01)
criterion = nn.MSELoss()

inputs = torch.randn((10, 10))
targets = torch.randn((10, 1))

best_loss = float('inf')
trigger_times = 0
patience = 2

for epoch in range(10):
    optimizer.zero_grad()
    outputs = model(inputs)
    loss = criterion(outputs, targets)
    loss.backward()
    optimizer.step()

    if loss < best_loss:
      best_loss = loss
      trigger_times = 0
    else:
      trigger_times += 1
      if trigger_times >= patience:
        print('ealry stopping')
        break

    print(f"epoch {epoch} loss {loss.item()}")
print("training ended")

epoch 0 loss 2.5702648162841797
epoch 1 loss 2.120114326477051
epoch 2 loss 1.8308303356170654
epoch 3 loss 1.635965347290039
epoch 4 loss 1.4983599185943604
epoch 5 loss 1.3967968225479126
epoch 6 loss 1.3185936212539673
epoch 7 loss 1.255816102027893
epoch 8 loss 1.203481912612915
epoch 9 loss 1.1584075689315796
training ended
