In [ ]:
import torch
import numpy as np 

In [ ]:
data = [[1,2],[3,4]]
a = torch.tensor(data)
a

tensor([[1, 2],
        [3, 4]])

In [ ]:
array = np.array(data)
np = torch.from_numpy(array)
np

tensor([[1, 2],
        [3, 4]])

In [ ]:
ones = torch.ones_like(a)
print(ones)
rands = torch.rand_like(a,dtype=torch.float)
print(rands)

tensor([[1, 1],
        [1, 1]])
tensor([[0.8875, 0.5392],
        [0.9601, 0.8830]])


In [ ]:
shape = (3,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f"rand tensor: \n {rand_tensor} \n")
print(f"ones tensor: \n {ones_tensor} \n")
print(f"zero tensor: \n {zeros_tensor} \n")

rand tensor: 
 tensor([[0.6079, 0.4384, 0.8422],
        [0.6681, 0.9703, 0.6813],
        [0.4544, 0.7294, 0.0228]]) 

ones tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 

zero tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) 



In [ ]:
tensor = torch.rand(5,5)
print(f"tensor datatype: {tensor.dtype}")
print(f"tensor shape: {tensor.shape}")
print(f"tensor device: {tensor.device}")

tensor datatype: torch.float32
tensor shape: torch.Size([5, 5])
tensor device: cpu


In [ ]:
if torch.cuda.is_available():
  tensor = tensor.to("cuda")

In [ ]:
tensor = torch.ones(3,3)
tensor[:,2] = 0
print(tensor)

tensor([[1., 1., 0.],
        [1., 1., 0.],
        [1., 1., 0.]])


In [ ]:
t = torch.cat([tensor,tensor],dim=1)
print(t)

tensor([[1., 1., 0., 1., 1., 0.],
        [1., 1., 0., 1., 1., 0.],
        [1., 1., 0., 1., 1., 0.]])


In [ ]:
print(f"mul tensor: \n {tensor.mul(tensor)} \n")
print(f"tensor*tensor: \n {tensor*tensor} \n")

mul tensor: 
 tensor([[1., 1., 0.],
        [1., 1., 0.],
        [1., 1., 0.]]) 

tensor*tensor: 
 tensor([[1., 1., 0.],
        [1., 1., 0.],
        [1., 1., 0.]]) 



In [ ]:
print(f"tensor.matmul(tensor.T): \n {tensor.matmul(tensor.T)} \n")
print(f"tensor @ tensor.T: \n {tensor @ tensor.T} \n")

tensor.matmul(tensor.T): 
 tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]) 

tensor @ tensor.T: 
 tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]) 



In [ ]:
print(tensor,"\n")
tensor.add_(9)
print(tensor)

tensor([[1., 1., 0.],
        [1., 1., 0.],
        [1., 1., 0.]]) 

tensor([[10., 10.,  9.],
        [10., 10.,  9.],
        [10., 10.,  9.]])


In [ ]:
v = torch.ones(5)
print(v)
b = v.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
